#! /bin/sh

bspc config border_width        2
bspc config window_gap          6
bspc config normal_border_color \#AFAEAB
bspc config focused_border_color \#3F3E3B

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config leaf_monocle true
bspc config focus_by_distance   true
bspc config -m eDP1 top_padding 25
bspc config focus_follows_pointer true

bspc monitor eDP1 -d I II III IV V
bspc monitor HDMI2 -d VI VII VIII IX X

#bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
